name: Clean up PR description

on:
  # see https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_target
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened
      - edited
    branches:
      - main
  workflow_call:
# see https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
permissions:
  pull-requests: write

jobs:
  check_labels:
    name: Remove html comments
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          repository: napari/shared-workflows
          ref: main
          persist-credentials: 'false'
      # install python and requests
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d # v10.0.1
        with:
          version: "latest"
      - name: Remove html comments
        env:
          GH_PR_NUMBER: ${{ github.event.number }}
          GH_REPO_URL: ${{ github.event.repository.url}}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        run: |
          uv run --script scripts/remove_html_comments_from_pr.py
