---
name: 'Update PR Triage Board'

on:
  schedule:
    - cron: '0 */4 * * *'  # Run every 4 hours
  workflow_dispatch:

permissions: {}

jobs:
  pr-triage:
    runs-on: ubuntu-latest
    steps:
      - name: Update PR Triage Board
        uses: jupyter/pr-triage-board-bot@e2765b29ea22f204088785ff982b99580d8f0193  # main @ Apr 24, 2026
        with:
          organization: 'napari'
          project-number: '35'
          gh-app-id: '3461445'
          gh-app-installation-id: '126023418'
          gh-app-private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}
          # repositories: 'napari'  # queries entire org unless comma-separated repos are added here
